from __future__ import annotations

import csv
import json
import os
import subprocess
import threading
import time
from dataclasses import asdict
from pathlib import Path
from typing import Any, Callable, Iterable, Sequence

import numpy as np

from uavgpr_simlab.core.postprocess import merge_available_bscan_for_input, candidate_out_files_for_input
from uavgpr_simlab.core.runner import resolve_manifest_path

BSCAN_ALIAS = {
    "raw": "raw_bscan.npy",
    "target_only": "target_only_bscan.npy",
    "background_only": "background_only_bscan.npy",
    "clutter_only": "clutter_only_bscan.npy",
    "air_only": "air_only_bscan.npy",
}

LEGACY_BSCAN_ALIAS = {
    "target_only": "target_bscan.npy",
    "background_only": "background_bscan.npy",
    "clutter_only": "clutter_bscan.npy",
    "air_only": "air_bscan.npy",
}


def _bscan_path(out_dir: Path, variant: str) -> Path:
    canonical = out_dir / BSCAN_ALIAS.get(variant, f"{variant}_bscan.npy")
    if canonical.exists():
        return canonical
    legacy = LEGACY_BSCAN_ALIAS.get(variant)
    if legacy and (out_dir / legacy).exists():
        return out_dir / legacy
    return canonical


def _jsonable(x: Any) -> Any:
    if isinstance(x, Path):
        return str(x)
    if hasattr(x, "tolist"):
        return x.tolist()
    if isinstance(x, (np.floating, np.integer)):
        return x.item()
    return x


def _workspace_from_manifest(manifest_csv: str | Path) -> Path:
    return Path(manifest_csv).expanduser().resolve().parent.parent


def _rel(path: str | Path, base: str | Path) -> str:
    p = Path(path).resolve()
    b = Path(base).resolve()
    try:
        return p.relative_to(b).as_posix()
    except Exception:
        return p.as_posix()


def _load_manifest_rows(manifest_csv: str | Path) -> list[dict[str, str]]:
    with Path(manifest_csv).open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _select_one_case_per_family(rows: list[dict[str, str]]) -> list[str]:
    seen: dict[str, str] = {}
    for row in rows:
        fam = row.get("family") or "unknown"
        cid = row.get("case_id") or ""
        if cid and fam not in seen:
            seen[fam] = cid
    # Preserve first-appearance order in manifest.
    return list(seen.values())


def _expected_shape_from_rows(case_rows: list[dict[str, str]]) -> tuple[int, int, float]:
    row = case_rows[0]
    traces = int(float(row.get("n_traces") or row.get("trace_count") or 1))
    time_window = float(row.get("time_window_ns") or 0.0)
    samples = 0
    # Prefer axis file if present; manifest generated by v0.8.0-alpha.2 stores it.
    manifest_csv = row.get("__manifest_csv", "")
    if manifest_csv and row.get("time_axis_ns_npy"):
        axis = resolve_manifest_path(row["time_axis_ns_npy"], manifest_csv)
        if axis.exists():
            try:
                samples = int(np.load(axis).shape[0])
            except Exception:
                samples = 0
    if samples <= 0:
        samples = 501
    return samples, traces, time_window


def resample_bscan(data: np.ndarray, samples: int, traces: int) -> np.ndarray:
    """Return samples x traces B-scan aligned to the SceneWorld contract."""
    x = np.asarray(data, dtype=np.float32)
    if x.ndim == 1:
        x = x[:, None]
    if x.shape[0] != samples:
        old = np.linspace(0.0, 1.0, x.shape[0], dtype=np.float32)
        new = np.linspace(0.0, 1.0, samples, dtype=np.float32)
        out = np.empty((samples, x.shape[1]), dtype=np.float32)
        for j in range(x.shape[1]):
            out[:, j] = np.interp(new, old, x[:, j]).astype(np.float32)
        x = out
    if x.shape[1] < traces:
        pad = np.full((samples, traces - x.shape[1]), np.nan, dtype=np.float32)
        x = np.concatenate([x, pad], axis=1)
    elif x.shape[1] > traces:
        x = x[:, :traces]
    return x.astype(np.float32, copy=False)


def inspect_bscan_array(path: str | Path, expected_shape: tuple[int, int] | None = None) -> dict[str, Any]:
    p = Path(path)
    rep: dict[str, Any] = {"path": str(p), "exists": p.exists()}
    if not p.exists():
        rep.update({"ok": False, "reason": "missing"})
        return rep
    try:
        arr = np.load(p)
        finite = np.isfinite(arr)
        rep.update({
            "shape": list(arr.shape),
            "has_nan": bool(np.isnan(arr).any()),
            "has_inf": bool(np.isinf(arr).any()),
            "finite_count": int(finite.sum()),
            "min": float(np.nanmin(arr)) if finite.any() else None,
            "max": float(np.nanmax(arr)) if finite.any() else None,
            "mean": float(np.nanmean(arr)) if finite.any() else None,
            "std": float(np.nanstd(arr)) if finite.any() else None,
        })
        if expected_shape is not None:
            rep["shape_matches_expected"] = list(arr.shape) == list(expected_shape)
        rep["ok"] = bool(finite.any() and not np.isinf(arr).any() and (expected_shape is None or list(arr.shape) == list(expected_shape)))
    except Exception as exc:
        rep.update({"ok": False, "reason": str(exc)})
    return rep


def build_case_bscan_qc(
    case_dir: str | Path,
    variants: Iterable[str] = ("raw", "target_only", "background_only", "clutter_only", "air_only"),
    expected_shape: tuple[int, int] | None = None,
    run_reports: dict[str, dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Inspect one SceneWorld case and write bscan_qc_report.json.

    The report schema is intentionally explicit because downstream PGDA-CSNet
    data preparation must not silently accept placeholder arrays or failed
    variants.  ``status`` is one of:

    - ``success``: every requested variant has a finite B-scan with expected shape,
      and ``clutter_gt_bscan.npy = raw_bscan.npy - target_bscan.npy`` was written.
    - ``failed``: at least one required B-scan is missing, contains invalid values,
      has the wrong shape, or clutter_gt cannot be computed.
    """
    case_dir = Path(case_dir)
    out_dir = case_dir / "outputs"
    variants = list(variants)
    rep: dict[str, Any] = {
        "schema": "uavgpr_simlab.bscan_qc.v2",
        "case_id": case_dir.name,
        "status": "failed",
        "expected_shape_samples_x_traces": list(expected_shape) if expected_shape else None,
        "variants": {},
        "raw_minus_target_computable": False,
        "clutter_gt_generated": False,
        "alignment_policy": "unknown",
        "resampled_variants": [],
        "native_shapes": {},
        "training_ready": False,
    }
    run_reports = run_reports or {}
    for v in variants:
        v_path = _bscan_path(out_dir, v)
        v_rep = inspect_bscan_array(v_path, expected_shape=expected_shape)
        run_rep = run_reports.get(v) or {}
        if run_rep:
            v_rep["gprmax_run_ok"] = bool(run_rep.get("ok"))
            v_rep["gprmax_error"] = run_rep.get("error", "")
            v_rep["merged_shape"] = run_rep.get("merged_shape")
            v_rep["expected_shape"] = run_rep.get("expected_shape")
            v_rep["out_files"] = run_rep.get("out_meta_file_list", [])
            v_rep["resampled"] = bool(run_rep.get("resampled", False))
            v_rep["raw_extract_path"] = run_rep.get("raw_extract_path", "")
            v_rep["aligned_shape"] = run_rep.get("aligned_shape")
            if run_rep.get("merged_shape"):
                rep["native_shapes"][v] = run_rep.get("merged_shape")
            if run_rep.get("resampled", False):
                rep["resampled_variants"].append(v)
        if not v_rep.get("exists"):
            v_rep["status"] = "failed"
            v_rep["reason"] = v_rep.get("reason") or "missing_bscan"
        elif v_rep.get("has_nan") or v_rep.get("has_inf"):
            v_rep["status"] = "failed"
            if run_rep.get("error"):
                v_rep["reason"] = "gprmax_output_not_replaced"
            else:
                v_rep["reason"] = "nan_or_inf_present"
        elif expected_shape is not None and not v_rep.get("shape_matches_expected"):
            v_rep["status"] = "failed"
            v_rep["reason"] = "shape_mismatch"
        elif v_rep.get("ok"):
            v_rep["status"] = "success"
        else:
            v_rep["status"] = "failed"
            v_rep["reason"] = v_rep.get("reason") or "not_finite_or_unreadable"
        rep["variants"][v] = v_rep

    raw_p = _bscan_path(out_dir, "raw")
    target_p = _bscan_path(out_dir, "target_only")
    clutter_gt_p = out_dir / "clutter_gt_bscan.npy"
    if raw_p.exists() and target_p.exists():
        try:
            raw = np.load(raw_p)
            target = np.load(target_p)
            if raw.shape == target.shape and np.isfinite(raw).all() and np.isfinite(target).all():
                clutter_gt = (raw - target).astype(np.float32)
                np.save(clutter_gt_p, clutter_gt)
                rep["raw_minus_target_computable"] = True
                rep["clutter_gt_generated"] = True
                rep["clutter_gt"] = inspect_bscan_array(clutter_gt_p, expected_shape=expected_shape)
            else:
                rep["clutter_gt_error"] = "raw/target contain invalid values or have mismatched shapes"
        except Exception as exc:
            rep["clutter_gt_error"] = str(exc)
    else:
        rep["clutter_gt_error"] = "raw_bscan.npy or target_only_bscan.npy missing"

    variants_ok = all(v.get("status") == "success" for v in rep["variants"].values())
    clutter_ok = bool(rep.get("raw_minus_target_computable") and rep.get("clutter_gt_generated") and rep.get("clutter_gt", {}).get("ok"))
    rep["alignment_policy"] = "explicit_resample_to_manifest_grid" if rep.get("resampled_variants") else "strict_native_or_already_aligned"
    rep["training_ready"] = bool(variants_ok and clutter_ok and not rep.get("resampled_variants"))
    rep["status"] = "success" if variants_ok and clutter_ok else "failed"
    (case_dir / "bscan_qc_report.json").write_text(json.dumps(rep, ensure_ascii=False, indent=2, default=_jsonable), encoding="utf-8")
    return rep

def _python_cmd(python_executable: str | Sequence[str]) -> list[str]:
    """Return a subprocess-safe Python command prefix.

    Do not use ``shlex.split`` for Windows paths such as
    ``D:\\Miniconda3\\python.exe``: POSIX-style splitting treats backslashes as
    escapes and can corrupt the executable path.  Conda mode passes a sequence
    explicitly from ``scripts/run_all_gprmax.py``.
    """

    if isinstance(python_executable, (list, tuple)):
        return [str(x) for x in python_executable if str(x).strip()]
    text = str(python_executable).strip().strip('"')
    if not text:
        return ["python"]
    return [text]


def _cleanup_stale_out_files(input_file: Path) -> list[str]:
    """Delete previous gprMax .out files for this input before a forced rerun."""

    deleted: list[str] = []
    for out_file in candidate_out_files_for_input(input_file):
        try:
            out_file.unlink()
            deleted.append(str(out_file))
        except FileNotFoundError:
            continue
        except Exception as exc:
            deleted.append(f"FAILED_TO_DELETE:{out_file}:{exc}")
    return deleted




def _classify_gprmax_failure(stdout: str, *, no_gpu: bool) -> tuple[str | None, bool, str]:
    """Classify common gprMax startup failures.

    Returns (error_code, fatal, user_message). Fatal errors are configuration
    problems that will repeat for every case/variant, so the batch runner should
    stop immediately instead of burning a full smoke/formal run.
    """

    text = str(stdout or "")
    lower = text.lower()
    if not no_gpu and ("no module named 'pycuda'" in lower or "pycuda package must be installed" in lower):
        return (
            "gpu_pycuda_missing",
            True,
            "GPU 模式需要 PyCUDA，但当前 Python 无法导入 pycuda。请使用 setup_gprmax_4090_windows.bat 创建/修复 gprMax conda 环境，或在设置页勾选“使用 conda run 调用 gprMax”。",
        )
    if not no_gpu and ("cuda" in lower and ("driver" in lower or "no cuda" in lower or "initialization" in lower)):
        return (
            "gpu_cuda_driver_unavailable",
            True,
            "当前 Python 能启动 gprMax，但 CUDA 驱动/GPU 初始化失败。请先运行 scripts\\Verify_4090_GPRMAX_GPU.bat 验证 nvidia-smi、nvcc、PyCUDA 和 gprMax -gpu。",
        )
    if "no module named gprmax" in lower or "no module named 'gprmax'" in lower:
        return (
            "gprmax_import_missing",
            True,
            "当前 Python 无法导入 gprMax。请确认 gprMax 源码目录、PYTHONPATH，或使用已安装 gprMax 的 conda 环境。",
        )
    return None, False, ""

def _run_one_gprmax(
    input_file: Path,
    *,
    gprmax_root: Path,
    python_executable: str | Sequence[str],
    n_traces: int,
    omp_threads: int,
    timeout_sec: int,
    no_gpu: bool,
    gpu_ids: list[int] | None = None,
    cancel_event: threading.Event | None = None,
) -> dict[str, Any]:
    base_cmd = _python_cmd(python_executable)
    cmd = base_cmd + ["-m", "gprMax", str(input_file), "-n", str(int(n_traces)), "--geometry-fixed"]
    if not no_gpu:
        cmd.append("-gpu")
        for gid in gpu_ids or []:
            cmd.append(str(int(gid)))
    env = os.environ.copy()
    env["OMP_NUM_THREADS"] = str(max(1, int(omp_threads)))
    # Make source-tree gprMax importable without requiring installation.
    env["PYTHONPATH"] = str(gprmax_root) + os.pathsep + env.get("PYTHONPATH", "")
    t0 = time.time()
    proc: subprocess.Popen[str] | None = None
    try:
        proc = subprocess.Popen(
            cmd,
            cwd=str(gprmax_root),
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        while True:
            if cancel_event is not None and cancel_event.is_set():
                try:
                    proc.terminate()
                    stdout, _ = proc.communicate(timeout=8)
                except subprocess.TimeoutExpired:
                    proc.kill()
                    stdout, _ = proc.communicate(timeout=8)
                return {
                    "cmd": cmd,
                    "returncode": proc.returncode,
                    "elapsed_sec": round(time.time() - t0, 3),
                    "stdout_tail": (stdout or "")[-6000:],
                    "ok": False,
                    "cancelled": True,
                    "error": "cancelled_by_user",
                }
            try:
                stdout, _ = proc.communicate(timeout=0.5)
                break
            except subprocess.TimeoutExpired:
                if time.time() - t0 > timeout_sec:
                    try:
                        proc.terminate()
                        stdout, _ = proc.communicate(timeout=8)
                    except subprocess.TimeoutExpired:
                        proc.kill()
                        stdout, _ = proc.communicate(timeout=8)
                    return {
                        "cmd": cmd,
                        "returncode": proc.returncode,
                        "elapsed_sec": round(time.time() - t0, 3),
                        "stdout_tail": (stdout or "")[-6000:],
                        "ok": False,
                        "error": f"timeout_after_{timeout_sec}_sec",
                    }
                continue
        ok = proc.returncode == 0
        rep = {
            "cmd": cmd,
            "returncode": proc.returncode,
            "elapsed_sec": round(time.time() - t0, 3),
            "stdout_tail": (stdout or "")[-6000:],
            "ok": ok,
        }
        if not ok:
            code, fatal, user_message = _classify_gprmax_failure(stdout or "", no_gpu=no_gpu)
            rep["error"] = code or f"gprMax_returncode_{proc.returncode}"
            if fatal:
                rep["fatal"] = True
                rep["user_message"] = user_message
        return rep
    except Exception as exc:
        if proc is not None and proc.poll() is None:
            try:
                proc.terminate()
            except Exception:
                pass
        return {
            "cmd": cmd,
            "returncode": None,
            "elapsed_sec": round(time.time() - t0, 3),
            "stdout_tail": "",
            "ok": False,
            "error": repr(exc),
        }


def _write_csv_rows(path: Path, rows: list[dict[str, str]]) -> None:
    if not rows:
        return
    fieldnames: list[str] = []
    for row in rows:
        for key in row.keys():
            if key.startswith("__"):
                continue
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", encoding="utf-8", newline="") as f:
        wr = csv.DictWriter(f, fieldnames=fieldnames)
        wr.writeheader()
        for row in rows:
            wr.writerow({k: row.get(k, "") for k in fieldnames})


def _update_dataset_summary(workspace: Path, report: dict[str, Any], rows: list[dict[str, str]]) -> None:
    summary_path = workspace / "reports" / "dataset_summary.json"
    if summary_path.exists():
        try:
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
        except Exception:
            summary = {}
    else:
        summary = {}
    cases = report.get("cases", {})
    case_status = {cid: c.get("bscan_qc", {}).get("status", "failed") for cid, c in cases.items()}
    resampled_cases = [cid for cid, c in cases.items() if c.get("bscan_qc", {}).get("resampled_variants")]
    training_ready_cases = [cid for cid, c in cases.items() if c.get("bscan_qc", {}).get("training_ready")]
    summary["bscan_run_status"] = {
        "status": "success" if report.get("ok") else "failed",
        "case_count_run": len(case_status),
        "success_cases": sum(1 for s in case_status.values() if s == "success"),
        "failed_cases": sum(1 for s in case_status.values() if s != "success"),
        "case_status": case_status,
        "qc_mode": report.get("qc_mode", "strict_native"),
        "allow_resample": bool(report.get("allow_resample", False)),
        "training_ready": bool(report.get("training_ready", False)),
        "training_ready_cases": training_ready_cases,
        "resampled_cases": resampled_cases,
        "report_json": _rel(report.get("report_json", ""), workspace) if report.get("report_json") else "reports/sceneworld_bscan_run_report.json",
    }
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2, default=_jsonable), encoding="utf-8")

def run_sceneworld_bscan_from_manifest(
    manifest_csv: str | Path,
    *,
    gprmax_root: str | Path,
    variants: list[str] | None = None,
    one_case_per_family: bool = True,
    max_cases: int = 0,
    python_executable: str | Sequence[str] = "python",
    omp_threads: int = 1,
    timeout_sec: int = 3600,
    no_gpu: bool = True,
    gpu_ids: list[int] | None = None,
    force: bool = False,
    allow_resample: bool = False,
    progress_callback: Callable[[Any], None] | None = None,
    cancel_event: threading.Event | None = None,
    skip_completed: bool = True,
    rerun_failed_only: bool = False,
) -> dict[str, Any]:
    """Run gprMax for SceneWorld rows and replace placeholder B-scans.

    This is intentionally a long-running offline utility.  For v080a3 it should
    normally be invoked with ``--one-case-per-family`` on the smoke manifest.
    """
    manifest_csv = Path(manifest_csv).resolve()
    workspace = _workspace_from_manifest(manifest_csv)
    rows = _load_manifest_rows(manifest_csv)
    for r in rows:
        r["__manifest_csv"] = str(manifest_csv)
    wanted_variants = set(variants or ["raw", "target_only", "background_only", "clutter_only", "air_only"])
    if rerun_failed_only:
        wanted_cases = {r.get("case_id", "") for r in rows if (r.get("bscan_status") or "not_run") == "failed" and r.get("case_id")}
    elif one_case_per_family:
        wanted_cases = set(_select_one_case_per_family(rows))
    else:
        wanted_cases = {r.get("case_id", "") for r in rows if r.get("case_id")}
    if max_cases and max_cases > 0:
        wanted_cases = set(list(wanted_cases)[: int(max_cases)])

    gprmax_root = Path(gprmax_root).resolve()
    report: dict[str, Any] = {
        "schema": "uavgpr_simlab.sceneworld_bscan_run.v1",
        "manifest": str(manifest_csv),
        "workspace": str(workspace),
        "gprmax_root": str(gprmax_root),
        "one_case_per_family": one_case_per_family,
        "variants": sorted(wanted_variants),
        "no_gpu": bool(no_gpu),
        "gpu_ids": list(gpu_ids or []),
        "allow_resample": bool(allow_resample),
        "skip_completed": bool(skip_completed),
        "rerun_failed_only": bool(rerun_failed_only),
        "qc_mode": "chain_resample" if allow_resample else "strict_native",
        "training_ready": False,
        "cases": {},
    }
    def emit(payload: Any) -> None:
        if progress_callback is not None:
            try:
                progress_callback(payload)
            except Exception:
                pass

    def emit_event(event: str, **payload: Any) -> None:
        data = {"event": event, **payload}
        if "message" not in data:
            cid = payload.get("case_id", "")
            variant = payload.get("variant", "")
            status = payload.get("status", "")
            data["message"] = " ".join(str(x) for x in [f"[{event}]", cid, variant, status] if x)
        emit(data)

    grouped: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        cid = row.get("case_id", "")
        if cid in wanted_cases:
            grouped.setdefault(cid, []).append(row)

    emit_event("job_started", workspace=str(workspace), manifest=str(manifest_csv), case_count=len(grouped), variants=sorted(wanted_variants), message=f"[job] start cases={len(grouped)} variants={','.join(sorted(wanted_variants))}")

    fatal_error = ""

    for cid, case_rows in grouped.items():
        if cancel_event is not None and cancel_event.is_set():
            report["cancelled"] = True
            emit_event("job_cancelled", status="cancelled", message="[job] cancelled before next case")
            break
        emit_event("case_started", case_id=cid, family=case_rows[0].get("family"), message=f"[case] {cid} start")
        case_dir = workspace / "models" / cid
        samples, traces, _time_window = _expected_shape_from_rows(case_rows)
        case_report: dict[str, Any] = {"family": case_rows[0].get("family"), "expected_shape": [samples, traces], "alignment_policy": "explicit_resample_to_manifest_grid" if allow_resample else "strict_native", "runs": {}}
        for row in case_rows:
            variant = row.get("variant", "")
            if variant not in wanted_variants:
                continue
            row_run_status = (row.get("bscan_status") or "not_run").strip()
            if rerun_failed_only and row_run_status != "failed":
                case_report["runs"][variant] = {"skipped": True, "reason": "not_failed", "ok": True}
                emit_event("variant_skipped", case_id=cid, variant=variant, status="skipped", reason="not_failed", message=f"[skip] {cid} / {variant}: not failed")
                continue
            if cancel_event is not None and cancel_event.is_set():
                case_report["runs"][variant] = {"ok": False, "cancelled": True, "error": "cancelled_by_user"}
                emit_event("variant_done", case_id=cid, variant=variant, status="failed", error="cancelled_by_user", message=f"[cancelled] {cid} / {variant}")
                break
            out_name = BSCAN_ALIAS.get(variant, f"{variant}_bscan.npy")
            out_path = case_dir / "outputs" / out_name
            if skip_completed and out_path.exists() and not force:
                try:
                    arr = np.load(out_path)
                    if np.isfinite(arr).any() and list(arr.shape) == [samples, traces] and row_run_status == "success":
                        case_report["runs"][variant] = {"skipped": True, "reason": "existing finite aligned bscan", "ok": True}
                        emit_event("variant_skipped", case_id=cid, variant=variant, status="skipped", bscan_path=str(out_path), message=f"[skip] {cid} / {variant}: existing success")
                        continue
                except Exception:
                    pass
            inp = resolve_manifest_path(row.get("input_file", ""), manifest_csv)
            emit_event("variant_started", case_id=cid, variant=variant, input_file=str(inp), message=f"[run] {cid} / {variant} -> {inp.name}")
            if force:
                run_rep_cleanup = _cleanup_stale_out_files(inp)
            else:
                run_rep_cleanup = []
            run_rep = _run_one_gprmax(inp, gprmax_root=gprmax_root, python_executable=python_executable, n_traces=traces, omp_threads=omp_threads, timeout_sec=timeout_sec, no_gpu=no_gpu, gpu_ids=gpu_ids, cancel_event=cancel_event)
            if run_rep_cleanup:
                run_rep["stale_out_files_deleted"] = run_rep_cleanup
            if run_rep["ok"]:
                merged = merge_available_bscan_for_input(inp)
                if merged is None:
                    run_rep["ok"] = False
                    run_rep["error"] = "gprMax completed but no readable .out files were found"
                else:
                    arr, meta = merged
                    original_shape = list(np.asarray(arr).shape)
                    expected_shape = [int(samples), int(traces)]
                    run_rep["merged_shape"] = original_shape
                    run_rep["expected_shape"] = expected_shape
                    run_rep["resampled"] = False
                    run_rep["out_meta_files"] = len(meta.get("files", [])) if isinstance(meta, dict) else None
                    run_rep["out_meta_file_list"] = [str(x.get("file", "")) for x in meta.get("files", [])] if isinstance(meta, dict) else []
                    raw_extract_path = case_dir / "outputs" / f"{variant}_bscan_extracted_raw.npy"
                    raw_extract_path.parent.mkdir(parents=True, exist_ok=True)
                    np.save(raw_extract_path, np.asarray(arr, dtype=np.float32))
                    run_rep["raw_extract_path"] = _rel(raw_extract_path, workspace)
                    if original_shape != expected_shape and not allow_resample:
                        run_rep["ok"] = False
                        run_rep["error"] = f"shape_mismatch_without_resample: got {original_shape}, expected {expected_shape}. This usually means gprMax native time samples differ from the manifest ML grid. Use a chain-validation profile with explicit resampling for smoke checks; keep strict mode for pilot/formal data acceptance."
                    else:
                        if original_shape != expected_shape:
                            aligned = resample_bscan(np.asarray(arr, dtype=np.float32), samples=samples, traces=traces)
                            run_rep["resampled"] = True
                            run_rep["resample_reason"] = "explicit_chain_validation_alignment_to_manifest_grid"
                        else:
                            aligned = np.asarray(arr, dtype=np.float32)
                        out_path.parent.mkdir(parents=True, exist_ok=True)
                        np.save(out_path, aligned)
                        exact = case_dir / "outputs" / f"{variant}_bscan.npy"
                        if exact != out_path:
                            np.save(exact, aligned)
                        run_rep["bscan_path"] = _rel(out_path, workspace)
                        run_rep["aligned_shape"] = list(aligned.shape)
                        emit_event("variant_output_ready", case_id=cid, variant=variant, bscan_path=str(out_path), time_window_ns=float(_time_window), shape=list(aligned.shape), status="success", elapsed_sec=run_rep.get("elapsed_sec"), message=f"[bscan] {cid} / {variant} -> {out_path.name}")
            if run_rep.get("stdout_tail"):
                emit(f"[log] {cid} / {variant}: {str(run_rep.get('stdout_tail'))[-1200:]}")
            if run_rep.get("ok"):
                emit_event("variant_done", case_id=cid, variant=variant, status="success", bscan_path=str(out_path), elapsed_sec=run_rep.get("elapsed_sec"), message=f"[ok] {cid} / {variant}")
            else:
                err = run_rep.get('error') or run_rep.get('returncode')
                emit_event("variant_done", case_id=cid, variant=variant, status="failed", error=str(err), elapsed_sec=run_rep.get("elapsed_sec"), message=f"[failed] {cid} / {variant}: {err}")
                if run_rep.get("fatal"):
                    fatal_error = str(run_rep.get("user_message") or run_rep.get("error") or err)
                    emit_event("job_fatal_error", status="failed", error=str(run_rep.get("error") or err), message=f"[fatal] {fatal_error}")
                    case_report["runs"][variant] = run_rep
                    break
            case_report["runs"][variant] = run_rep
        case_report["bscan_qc"] = build_case_bscan_qc(case_dir, variants=sorted(wanted_variants), expected_shape=(samples, traces), run_reports=case_report.get("runs", {}))
        case_report["status"] = case_report["bscan_qc"].get("status", "failed")
        report["cases"][cid] = case_report
        # Write per-case status immediately so the History page can refresh while
        # a long smoke/pilot job is still running. Final propagation below still
        # rewrites the complete manifest after the job ends.
        for row_status in rows:
            if row_status.get("case_id") == cid:
                v_status = row_status.get("variant", "")
                run_status = case_report.get("runs", {}).get(v_status, {})
                v_qc = (case_report.get("bscan_qc", {}).get("variants", {}) or {}).get(v_status, {})
                row_status["bscan_status"] = str(v_qc.get("status") or ("success" if run_status.get("ok") else "failed"))
                row_status["bscan_error"] = "" if row_status["bscan_status"] == "success" else str(run_status.get("error") or v_qc.get("reason") or run_status.get("reason") or run_status.get("stdout_tail", "")[-240:])
        _write_csv_rows(manifest_csv, rows)
        partial_report = {**report, "report_json": str(workspace / "reports" / "sceneworld_bscan_run_report.json")}
        _update_dataset_summary(workspace, partial_report, rows)
        qc_path = str(case_dir / "bscan_qc_report.json")
        emit_event("case_qc_done", case_id=cid, family=case_report.get("family"), status=case_report["status"], qc_report_json=qc_path, message=f"[case] {cid} status={case_report['status']}")
        if fatal_error:
            report["fatal_error"] = fatal_error
            break

    # Propagate run status into manifest rows.  This prevents failed or partially
    # generated case packages from being treated as training-ready.
    for row in rows:
        cid = row.get("case_id", "")
        if cid in report["cases"]:
            case_status = report["cases"][cid].get("status", "failed")
            row["bscan_status"] = case_status
            v = row.get("variant", "")
            run_rep = report["cases"][cid].get("runs", {}).get(v, {})
            case_qc = report["cases"][cid].get("bscan_qc", {})
            v_qc = (case_qc.get("variants", {}) or {}).get(v, {})
            row["bscan_status"] = str(v_qc.get("status") or ("success" if run_rep.get("ok") else case_status))
            if row["bscan_status"] == "success":
                row["bscan_error"] = ""
            else:
                row["bscan_error"] = str(run_rep.get("error") or v_qc.get("reason") or run_rep.get("reason") or run_rep.get("stdout_tail", "")[-240:])
        else:
            row.setdefault("bscan_status", "not_run")
            row.setdefault("bscan_error", "")
    _write_csv_rows(manifest_csv, rows)

    report["case_count"] = len(report["cases"])
    report["ok"] = (not report.get("cancelled")) and all(c.get("bscan_qc", {}).get("status") == "success" for c in report["cases"].values()) if report["cases"] else False
    report["training_ready"] = bool(report["ok"] and not allow_resample and all(c.get("bscan_qc", {}).get("training_ready") for c in report["cases"].values()))
    report["resampled_cases"] = [cid for cid, c in report["cases"].items() if c.get("bscan_qc", {}).get("resampled_variants")]
    out = workspace / "reports" / "sceneworld_bscan_run_report.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    report["report_json"] = str(out)
    out.write_text(json.dumps(report, ensure_ascii=False, indent=2, default=_jsonable), encoding="utf-8")
    _update_dataset_summary(workspace, report, rows)
    emit_event("job_done", status="success" if report.get("ok") else "failed", report_json=str(out), case_count=report.get("case_count"), message=f"[job] done status={'success' if report.get('ok') else 'failed'} cases={report.get('case_count')}")
    return report


def check_sceneworld_case_package(workspace: str | Path, manifest_csv: str | Path | None = None) -> dict[str, Any]:
    workspace = Path(workspace).resolve()
    if manifest_csv is None:
        found = sorted((workspace / "datasets").glob("*_manifest.csv"))
        if not found:
            raise FileNotFoundError(f"No manifest found under {workspace / 'datasets'}")
        manifest_csv = found[-1]
    manifest_csv = Path(manifest_csv).resolve()
    rows = _load_manifest_rows(manifest_csv)
    cases = sorted({r.get("case_id", "") for r in rows if r.get("case_id")})
    required_case_files = [
        "raw.in", "target_only.in", "background_only.in", "clutter_only.in", "air_only.in",
        "scene_world.json", "metadata_summary.json", "model_preview.png", "variant_preview.png", "bscan_qc_report.json",
        "labels/interface_gt.npy", "labels/layer_gt.npy", "labels/layer_gt_x_axis_m.npy", "labels/layer_gt_y_axis_m.npy",
        "labels/interface_mask_bscan.npy", "labels/layer_mask_bscan.npy",
        "outputs/raw_bscan.npy", "outputs/target_only_bscan.npy", "outputs/background_only_bscan.npy", "outputs/clutter_only_bscan.npy", "outputs/air_only_bscan.npy", "outputs/clutter_gt_bscan.npy",
        "outputs/time_axis_ns.npy", "outputs/distance_axis_m.npy", "outputs/tx_x_axis_m.npy", "outputs/rx_x_axis_m.npy", "outputs/midpoint_x_axis_m.npy",
    ]
    rep: dict[str, Any] = {"workspace": str(workspace), "manifest": str(manifest_csv), "case_count": len(cases), "cases": {}, "ok": True}
    for cid in cases:
        cdir = workspace / "models" / cid
        missing = [x for x in required_case_files if not (cdir / x).exists()]
        qc_path = cdir / "bscan_qc_report.json"
        qc_status = "missing"
        if qc_path.exists():
            try:
                qc_status = json.loads(qc_path.read_text(encoding="utf-8")).get("status", "unknown")
            except Exception as exc:
                qc_status = f"unreadable: {exc}"
        rep["cases"][cid] = {"missing": missing, "qc_status": qc_status}
        if missing:
            rep["ok"] = False
    return rep
